//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nexdox.com/NXPAFOnline", ConfigurationName="ServiceReference1.clsPAFSoap")]
    public interface clsPAFSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nexdox.com/NXPAFOnline/CheckAMMSDVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CheckAMMSDVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nexdox.com/NXPAFOnline/GetAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.stAddress> GetAddressAsync(string nsHouseName, string nsHouseNumber, string nsPostCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nexdox.com/NXPAFOnline/GetFromPipedAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.MatchResults> GetFromPipedAddressAsync(string PipedAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nexdox.com/NXPAFOnline/GetAddressesByPostcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetAddressesByPostcodeResponse> GetAddressesByPostcodeAsync(ServiceReference1.GetAddressesByPostcodeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public partial class stAddress
    {
        
        private string sFlatNumberField;
        
        private string sHouseNumberField;
        
        private string sStreetField;
        
        private string sNumStreetField;
        
        private string sBuildingNameField;
        
        private string sOrganisationField;
        
        private string sLocalityField;
        
        private string sTownField;
        
        private string sCountyField;
        
        private string sPostCodeField;
        
        private string sDPSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sFlatNumber
        {
            get
            {
                return this.sFlatNumberField;
            }
            set
            {
                this.sFlatNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sHouseNumber
        {
            get
            {
                return this.sHouseNumberField;
            }
            set
            {
                this.sHouseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sStreet
        {
            get
            {
                return this.sStreetField;
            }
            set
            {
                this.sStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sNumStreet
        {
            get
            {
                return this.sNumStreetField;
            }
            set
            {
                this.sNumStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sBuildingName
        {
            get
            {
                return this.sBuildingNameField;
            }
            set
            {
                this.sBuildingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sOrganisation
        {
            get
            {
                return this.sOrganisationField;
            }
            set
            {
                this.sOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sLocality
        {
            get
            {
                return this.sLocalityField;
            }
            set
            {
                this.sLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sTown
        {
            get
            {
                return this.sTownField;
            }
            set
            {
                this.sTownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sCounty
        {
            get
            {
                return this.sCountyField;
            }
            set
            {
                this.sCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sPostCode
        {
            get
            {
                return this.sPostCodeField;
            }
            set
            {
                this.sPostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sDPS
        {
            get
            {
                return this.sDPSField;
            }
            set
            {
                this.sDPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public partial class DeliveryRecord
    {
        
        private string outcodeField;
        
        private string incodeField;
        
        private string postCodeTypeField;
        
        private string sequenceField;
        
        private string dPSField;
        
        private int buildingNumberField;
        
        private string buildingNameField;
        
        private string subBuildingNameField;
        
        private string organisationNameField;
        
        private string departmentNameField;
        
        private string pOBoxNumberField;
        
        private int noOfHouseholdsField;
        
        private string smallUserOrganisationField;
        
        private int addressKeyField;
        
        private int organisationKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Outcode
        {
            get
            {
                return this.outcodeField;
            }
            set
            {
                this.outcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Incode
        {
            get
            {
                return this.incodeField;
            }
            set
            {
                this.incodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PostCodeType
        {
            get
            {
                return this.postCodeTypeField;
            }
            set
            {
                this.postCodeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DPS
        {
            get
            {
                return this.dPSField;
            }
            set
            {
                this.dPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int BuildingNumber
        {
            get
            {
                return this.buildingNumberField;
            }
            set
            {
                this.buildingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BuildingName
        {
            get
            {
                return this.buildingNameField;
            }
            set
            {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SubBuildingName
        {
            get
            {
                return this.subBuildingNameField;
            }
            set
            {
                this.subBuildingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OrganisationName
        {
            get
            {
                return this.organisationNameField;
            }
            set
            {
                this.organisationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DepartmentName
        {
            get
            {
                return this.departmentNameField;
            }
            set
            {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string POBoxNumber
        {
            get
            {
                return this.pOBoxNumberField;
            }
            set
            {
                this.pOBoxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int NoOfHouseholds
        {
            get
            {
                return this.noOfHouseholdsField;
            }
            set
            {
                this.noOfHouseholdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SmallUserOrganisation
        {
            get
            {
                return this.smallUserOrganisationField;
            }
            set
            {
                this.smallUserOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int AddressKey
        {
            get
            {
                return this.addressKeyField;
            }
            set
            {
                this.addressKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int OrganisationKey
        {
            get
            {
                return this.organisationKeyField;
            }
            set
            {
                this.organisationKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public partial class ThoroughFareRecord
    {
        
        private string thoroughFareNameField;
        
        private string thoroughFareDescriptorField;
        
        private string depThoroughFareNameField;
        
        private string depThoroughFareDescriptorField;
        
        private bool postcodeFoundField;
        
        private bool localityAndThoroughFareMatchedField;
        
        private bool localityAndDepThoroughFareMatchedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ThoroughFareName
        {
            get
            {
                return this.thoroughFareNameField;
            }
            set
            {
                this.thoroughFareNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ThoroughFareDescriptor
        {
            get
            {
                return this.thoroughFareDescriptorField;
            }
            set
            {
                this.thoroughFareDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DepThoroughFareName
        {
            get
            {
                return this.depThoroughFareNameField;
            }
            set
            {
                this.depThoroughFareNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DepThoroughFareDescriptor
        {
            get
            {
                return this.depThoroughFareDescriptorField;
            }
            set
            {
                this.depThoroughFareDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool PostcodeFound
        {
            get
            {
                return this.postcodeFoundField;
            }
            set
            {
                this.postcodeFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool LocalityAndThoroughFareMatched
        {
            get
            {
                return this.localityAndThoroughFareMatchedField;
            }
            set
            {
                this.localityAndThoroughFareMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool LocalityAndDepThoroughFareMatched
        {
            get
            {
                return this.localityAndDepThoroughFareMatchedField;
            }
            set
            {
                this.localityAndDepThoroughFareMatchedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public partial class LocalityRecord
    {
        
        private string postTownField;
        
        private string depLocalityField;
        
        private string doubleDepLocalityField;
        
        private bool postcodeFoundField;
        
        private bool postCodeAndTownMatchedField;
        
        private bool postCodeAndDepLocalityMatchedField;
        
        private bool postCodeAndDoubleDepLocalityMatchedField;
        
        private UKCountry uKCountryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PostTown
        {
            get
            {
                return this.postTownField;
            }
            set
            {
                this.postTownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepLocality
        {
            get
            {
                return this.depLocalityField;
            }
            set
            {
                this.depLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DoubleDepLocality
        {
            get
            {
                return this.doubleDepLocalityField;
            }
            set
            {
                this.doubleDepLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool PostcodeFound
        {
            get
            {
                return this.postcodeFoundField;
            }
            set
            {
                this.postcodeFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool PostCodeAndTownMatched
        {
            get
            {
                return this.postCodeAndTownMatchedField;
            }
            set
            {
                this.postCodeAndTownMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool PostCodeAndDepLocalityMatched
        {
            get
            {
                return this.postCodeAndDepLocalityMatchedField;
            }
            set
            {
                this.postCodeAndDepLocalityMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool PostCodeAndDoubleDepLocalityMatched
        {
            get
            {
                return this.postCodeAndDoubleDepLocalityMatchedField;
            }
            set
            {
                this.postCodeAndDoubleDepLocalityMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public UKCountry UKCountryCode
        {
            get
            {
                return this.uKCountryCodeField;
            }
            set
            {
                this.uKCountryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public enum UKCountry
    {
        
        /// <remarks/>
        NoUKCountryMatch,
        
        /// <remarks/>
        EnglandOrWales,
        
        /// <remarks/>
        NorthernIreland,
        
        /// <remarks/>
        Scotland,
        
        /// <remarks/>
        ChannelIslands,
        
        /// <remarks/>
        IsleOfMan,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public partial class MatchResults
    {
        
        private MatchType matchTypeField;
        
        private LocalityRecord localityField;
        
        private ThoroughFareRecord thoroughFareField;
        
        private DeliveryRecord deliveryField;
        
        private LocalityRecord localityWelshField;
        
        private ThoroughFareRecord thoroughFareWelshField;
        
        private DeliveryRecord deliveryWelshField;
        
        private string originalAddressPipedField;
        
        private string[] originalAddressField;
        
        private string[] cleanAddressField;
        
        private bool welshDeliveryAlternativeField;
        
        private bool welshDeliveryMatchField;
        
        private string barcode4StateField;
        
        private int thoroughFareFieldField;
        
        private int depThoroughFareFieldField;
        
        private int depLocalityFieldField;
        
        private int doubleDepLocalityFieldField;
        
        private int postTownFieldField;
        
        private int postCodeFieldField;
        
        private int countryFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MatchType MatchType
        {
            get
            {
                return this.matchTypeField;
            }
            set
            {
                this.matchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LocalityRecord Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ThoroughFareRecord ThoroughFare
        {
            get
            {
                return this.thoroughFareField;
            }
            set
            {
                this.thoroughFareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DeliveryRecord Delivery
        {
            get
            {
                return this.deliveryField;
            }
            set
            {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LocalityRecord LocalityWelsh
        {
            get
            {
                return this.localityWelshField;
            }
            set
            {
                this.localityWelshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ThoroughFareRecord ThoroughFareWelsh
        {
            get
            {
                return this.thoroughFareWelshField;
            }
            set
            {
                this.thoroughFareWelshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DeliveryRecord DeliveryWelsh
        {
            get
            {
                return this.deliveryWelshField;
            }
            set
            {
                this.deliveryWelshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OriginalAddressPiped
        {
            get
            {
                return this.originalAddressPipedField;
            }
            set
            {
                this.originalAddressPipedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public string[] OriginalAddress
        {
            get
            {
                return this.originalAddressField;
            }
            set
            {
                this.originalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public string[] CleanAddress
        {
            get
            {
                return this.cleanAddressField;
            }
            set
            {
                this.cleanAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool WelshDeliveryAlternative
        {
            get
            {
                return this.welshDeliveryAlternativeField;
            }
            set
            {
                this.welshDeliveryAlternativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool WelshDeliveryMatch
        {
            get
            {
                return this.welshDeliveryMatchField;
            }
            set
            {
                this.welshDeliveryMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Barcode4State
        {
            get
            {
                return this.barcode4StateField;
            }
            set
            {
                this.barcode4StateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ThoroughFareField
        {
            get
            {
                return this.thoroughFareFieldField;
            }
            set
            {
                this.thoroughFareFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int DepThoroughFareField
        {
            get
            {
                return this.depThoroughFareFieldField;
            }
            set
            {
                this.depThoroughFareFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int DepLocalityField
        {
            get
            {
                return this.depLocalityFieldField;
            }
            set
            {
                this.depLocalityFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int DoubleDepLocalityField
        {
            get
            {
                return this.doubleDepLocalityFieldField;
            }
            set
            {
                this.doubleDepLocalityFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int PostTownField
        {
            get
            {
                return this.postTownFieldField;
            }
            set
            {
                this.postTownFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int PostCodeField
        {
            get
            {
                return this.postCodeFieldField;
            }
            set
            {
                this.postCodeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int CountryField
        {
            get
            {
                return this.countryFieldField;
            }
            set
            {
                this.countryFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nexdox.com/NXPAFOnline")]
    public enum MatchType
    {
        
        /// <remarks/>
        NoMatch,
        
        /// <remarks/>
        International,
        
        /// <remarks/>
        FullMatchType1,
        
        /// <remarks/>
        FullMatchType2,
        
        /// <remarks/>
        FullMatchType3,
        
        /// <remarks/>
        FullMatchType4,
        
        /// <remarks/>
        PAFDatabaseNotAvailable,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressesByPostcode", WrapperNamespace="http://www.nexdox.com/NXPAFOnline", IsWrapped=true)]
    public partial class GetAddressesByPostcodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nexdox.com/NXPAFOnline", Order=0)]
        public string postcode;
        
        public GetAddressesByPostcodeRequest()
        {
        }
        
        public GetAddressesByPostcodeRequest(string postcode)
        {
            this.postcode = postcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressesByPostcodeResponse", WrapperNamespace="http://www.nexdox.com/NXPAFOnline", IsWrapped=true)]
    public partial class GetAddressesByPostcodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nexdox.com/NXPAFOnline", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAddressesByPostcodeResult;
        
        public GetAddressesByPostcodeResponse()
        {
        }
        
        public GetAddressesByPostcodeResponse(string[][] GetAddressesByPostcodeResult)
        {
            this.GetAddressesByPostcodeResult = GetAddressesByPostcodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface clsPAFSoapChannel : ServiceReference1.clsPAFSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class clsPAFSoapClient : System.ServiceModel.ClientBase<ServiceReference1.clsPAFSoap>, ServiceReference1.clsPAFSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public clsPAFSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(clsPAFSoapClient.GetBindingForEndpoint(endpointConfiguration), clsPAFSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public clsPAFSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(clsPAFSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public clsPAFSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(clsPAFSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public clsPAFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> CheckAMMSDVersionAsync()
        {
            return base.Channel.CheckAMMSDVersionAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.stAddress> GetAddressAsync(string nsHouseName, string nsHouseNumber, string nsPostCode)
        {
            return base.Channel.GetAddressAsync(nsHouseName, nsHouseNumber, nsPostCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MatchResults> GetFromPipedAddressAsync(string PipedAddress)
        {
            return base.Channel.GetFromPipedAddressAsync(PipedAddress);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAddressesByPostcodeResponse> ServiceReference1.clsPAFSoap.GetAddressesByPostcodeAsync(ServiceReference1.GetAddressesByPostcodeRequest request)
        {
            return base.Channel.GetAddressesByPostcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAddressesByPostcodeResponse> GetAddressesByPostcodeAsync(string postcode)
        {
            ServiceReference1.GetAddressesByPostcodeRequest inValue = new ServiceReference1.GetAddressesByPostcodeRequest();
            inValue.postcode = postcode;
            return ((ServiceReference1.clsPAFSoap)(this)).GetAddressesByPostcodeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.clsPAFSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.clsPAFSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.clsPAFSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://paf.nexdox.com/paf.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.clsPAFSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://paf.nexdox.com/paf.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            clsPAFSoap,
            
            clsPAFSoap12,
        }
    }
}
